version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: schemars
    versions:
    - 0.8.2
  - dependency-name: stainless_ffmpeg
    versions:
    - 0.2.4
    - 0.2.5
  - dependency-name: serde
    versions:
    - 1.0.122
    - 1.0.123
    - 1.0.124
  - dependency-name: mcai_worker_sdk
    versions:
    - 1.0.0-alpha3
    - 1.0.0-alpha5
  - dependency-name: serde_json
    versions:
    - 1.0.61
    - 1.0.62
